#!/bin/bash

case "$BLOCK_BUTTON" in
	1) amixer -q -D pulse sset Master toggle;;
	4) amixer -q -D pulse sset Master on && amixer -q -D pulse sset Master 5%+;;
	5) amixer -q -D pulse sset Master 5%-;;
esac

CURRENT_VOLUME=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{print $2}')
CURRENT_STATE=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{print $4}')
if [ "$CURRENT_STATE" == "off" ]
then
		COLOR="red"
		ICON='<span font="Font Awesome 5 Free"></span>'
else
		COLOR="#00E676"
		ICON='<span font="Font Awesome 5 Free"></span>'

fi
echo "<span color=\"$COLOR\">$ICON $CURRENT_VOLUME</span>"

/* vim:ft=sh
