#!/bin/bash
#
OPTION=$1

function backup() {
	pacman -Qe | awk '{print $1}' > packages.arch
	cp -R ~/.config/{i3,i3blocks,rofi,picom,ranger,dunst,alacritty} .config/
	cp -R ~/{.vimrc,.Xresources,.bashrc} .

}

function restore() {
	cp -R .config/* ~/.config/
	cp -R {.vimrc,.tmux.conf,.Xresources,.bashrc} ~/
}

function push() {
	echo "Coming soon"
}

function screenshot() {
	rm screenshots/*

	SLEEP="sleep 2"
	# 0. Fuse to single display for ease of screenshots
	
	$HOME/.local/bin/screenlayout reset
	# 1. Switch to empty workspace and take screenshot
	
	i3-msg workspace 9
	$SLEEP
	scrot screenshots/1-desktop.png
	
	# 2. Start alacritty
	
	i3-msg exec 'alacritty --class test'
	$SLEEP
	scrot screenshots/2-alacritty.png
	
	# 3. Screenshot of gaps
	
	i3-msg exec 'alacritty --class test -e "htop"'
	$SLEEP
	scrot screenshots/4-i3gaps.png
	
	kill $(ps ax | grep "alacritty --class test" | cut -f"1" -d" ")
	
	# 4. Ranger
	i3-msg exec 'alacritty --class test -e ranger /'
	$SLEEP
	scrot screenshots/6-ranger.png
	kill $(ps ax | grep "alacritty --class test" | cut -f"1" -d" ")
	
	# 5. vim
	i3-msg exec "alacritty --class test -e vim $HOME/.config/i3blocks/config"
	$SLEEP
	scrot screenshots/7-vim.png
	kill $(ps ax | grep "alacritty --class test" | cut -f"1" -d" ")
	
	# 6. rofi (Starting Feh for white background)
	i3-msg exec "feh -F $HOME/Pictures/wallhaven/nature/wallhaven-q6o997.jpg"
	$SLEEP
	i3-msg exec "rofi -show combi -width 35 -lines 6"
	sleep 2
	scrot screenshots/5-rofi.png
}
function default() {
	echo -e "Available options:

	a. Take backup of configurations
	   ./dotfiles backup

	b. Restore configurations
	   ./dotfiles restore

	c. Push configurations to github
	   ./dotfiles push
	"
}
case $OPTION in
	backup)
		backup
		;;
	restore)
		restore
		;;
	screenshot)
		screenshot
		;;
	push)
		push
		;;
	*)
		default
		;;
esac

# SETUP BASH_IT


