#!/bin/bash
#
OPTION=$1

function backup() {
	pacman -Qe | awk '{print $1}' > packages.arch
	cp -R ~/.config/{i3,i3blocks,rofi,picom,ranger,dunst} .config/
	cp -R ~/{.vimrc,.Xresources,.bashrc} .
}

function restore() {
	cp -R .config/* ~/.config/
	cp -R {.vimrc,.tmux.conf,.Xresources,.bashrc} ~/
}

function push() {
	echo "Coming soon"
}

function default() {
	echo -e "Available options:

	a. Take backup of configurations
	   ./dotfiles backup

	b. Restore configurations
	   ./dotfiles restore

	c. Push configurations to github
	   ./dotfiles push
	"
}
case $OPTION in
	backup)
		backup
		;;
	restore)
		restore
		;;
	push)
		push
		;;
	*)
		default
		;;
esac

# SETUP BASH_IT


