#! /bin/sh

blockdate=$(date +"%H:%M")

year=$(date '+%Y')
month=$(date '+%m')
case "$BLOCK_BUTTON" in
    1|2)
        date=$(date '+%A, %d. %B');;
    3)
        (( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
        date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')
esac
case "$BLOCK_BUTTON" in
    1|2|3)
export TERM=xterm
cal --color=always $month $year \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Fira Code 14" \
        -hide-scrollbar \
		-theme sidetab \
        -bw 2 \
        -theme-str '#window {width: 16%;height: 35%; anchor:southeast; location:northwest;}' \
        -eh 1 \
        -m -3 \
        -width -28 \
        -no-custom \
        -p "$date" > /dev/null 
    esac
echo "$blockdate"
